//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VATPRINT_CBSO_oldEntities : DbContext
    {
        public VATPRINT_CBSO_oldEntities()
            : base("name=VATPRINT_CBSO_oldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<VAT02_Security_GroupSecurity> VAT02_Security_GroupSecurity { get; set; }
        public DbSet<VAT02_Security_Menu> VAT02_Security_Menu { get; set; }
        public DbSet<VAT02_Security_User> VAT02_Security_User { get; set; }
        public DbSet<VAT02_Security_UserGroup> VAT02_Security_UserGroup { get; set; }
        public DbSet<VAT02_Security_UserInGroup> VAT02_Security_UserInGroup { get; set; }
        public DbSet<VAT02_UserData> VAT02_UserData { get; set; }
        public DbSet<VAT02_UserType> VAT02_UserType { get; set; }
    }
}
