//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT02_Security_User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public Nullable<int> Enable { get; set; }
        public string UserRealName { get; set; }
        public int CompanyID { get; set; }
        public int UserTypeID { get; set; }
        public string UserTypeName { get; set; }
        public int UserSystemEdition { get; set; }
        public string ExportSplitSymbol { get; set; }
        public string Remark { get; set; }
        public string Province { get; set; }
        public string ProductGroup { get; set; }
        public string InvoiceType { get; set; }
        public string Channel { get; set; }
        public Nullable<System.Guid> OnlineGuid { get; set; }
        public Nullable<bool> FlagXX { get; set; }
        public Nullable<bool> FlagLeave { get; set; }
        public string YProvince { get; set; }
        public string YProductGroup { get; set; }
        public string YChannel { get; set; }
        public string kbetr { get; set; }
        public Nullable<System.DateTime> NextChaPwdDate { get; set; }
    }
}
